del /s /q .\main\temp\*.*
del /s /q .\modules\AnalogIN\temp\*.*
del /s /q .\modules\analogOUT\temp\*.*
del /s /q .\modules\ControlKeypad\temp\*.*
del /s /q .\modules\Cylinders\temp\*.*
del /s /q .\modules\DigitalIO\temp\*.*
del /s /q .\modules\Numeric\temp\*.*
del /s /q .\modules\SerialTerminal\temp\*.*
del /s /q .\modules\SteperMotor\temp\*.*
del /s /q .\modules\Tank\temp\*.*
del /s /q .\modules\TestUnit\temp\*.*
del /s /q .\modules\TextDisplay\temp\*.*
