del /s /q .\main\temp\*.*
del /s /q .\modules\AnalogIN\temp\*.*
del /s /q .\modules\analogOUT\temp\*.*
del /s /q .\modules\ControlKeypad\temp\*.*
del /s /q .\modules\Cylinders\temp\*.*
del /s /q .\modules\DigitalIO\temp\*.*
del /s /q .\modules\ElevatorCab\temp\*.*
del /s /q .\modules\ElevatorCall\temp\*.*
del /s /q .\modules\Numeric\temp\*.*
del /s /q .\modules\NumKeypad\temp\*.*
del /s /q .\modules\PushKeypad\temp\*.*
del /s /q .\modules\SimpleMotor\temp\*.*
del /s /q .\modules\StepperMotor\temp\*.*
del /s /q .\modules\Tank\temp\*.*
del /s /q .\modules\TestUnit\temp\*.*
del /s /q .\modules\TextDisplay\temp\*.*
del /s /q .\modules\TrafficLight\temp\*.*
